version: '3.8'

services:
  # MySQL Database for Development
  mysql-dev:
    image: mysql:8.0
    container_name: kitrpc-mysql-dev
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - '3306:3306'
    volumes:
      - mysql_dev_data:/var/lib/mysql
      # Optional: Add init scripts if needed
      # - ./mysql/init:/docker-entrypoint-initdb.d
    networks:
      - kitrpc-dev-network
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
      timeout: 20s
      retries: 10
      interval: 30s
      start_period: 30s

  # Qdrant Vector Database
  qdrant:
    image: qdrant/qdrant:latest
    container_name: kitrpc-qdrant
    restart: unless-stopped
    ports:
      - '6333:6333' # HTTP API
      - '6334:6334' # gRPC API
    volumes:
      - qdrant_storage:/qdrant/storage
    environment:
      # Override/extend Qdrant configuration via env vars if needed
      # Example: adjust log level
      RUST_LOG: INFO
    networks:
      - kitrpc-dev-network
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:6333/health']
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

volumes:
  mysql_dev_data:
    driver: local
  qdrant_storage:
    driver: local

networks:
  kitrpc-dev-network:
    driver: bridge
