version: '3.8'

services:
  # MySQL Database for Development
  mysql-dev:
    image: mysql:8.0
    container_name: kitrpc-mysql-dev
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "3306:3306"
    volumes:
      - mysql_dev_data:/var/lib/mysql
      # Optional: Add init scripts if needed
      # - ./mysql/init:/docker-entrypoint-initdb.d
    networks:
      - kitrpc-dev-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
      interval: 30s
      start_period: 30s

volumes:
  mysql_dev_data:
    driver: local

networks:
  kitrpc-dev-network:
    driver: bridge